- src/js/directives/components/select-matching-type.js
> change option titles

- src/jade/index.jade
- src/jade/templates/directives/condition-input.jade
- src/jade/templates/directives/doubled-input.jade
- src/jade/templates/directives/field.jade
- src/js/directives/condition-input.js
- src/js/directives/doubled-input.js
- src/js/directives/field.js
- src/js/modules/conditions.js
- src/sass/app.sass
> Add is_between

- src/jade/index.jade
- src/jade/templates/decision-details.jade
- src/js/directives/skip-form.js
> skip form directive

- bower.json
- src/jade/index.jade
- src/js/app.js
> page loading

- src/jade/templates/history-list.jade
- src/js/configs/states.js
- src/js/controllers/history-list-controller.js
- src/js/modules/gandalf/models/table.js
- src/js/modules/gandalf/services/gandalf.js
live search by table name in history list
> live search by table name in history list

- bower.json
- src/jade/index.jade
- src/jade/templates/directives/decision-input.jade
- src/js/app.js
- src/js/configs/validate.js
> validate module add

- src/jade/templates/directives/decision-table.jade
https://nebo15.atlassian.net/browse/GDF-366
> Default title and default description unrequired

- src/jade/templates/directives/decision-input.jade
- src/jade/templates/modal/add-field.jade
- src/jade/templates/modal/add-project.jade
- src/jade/templates/tables-create.jade
- src/jade/templates/tables-edit.jade
- src/js/configs/language.js
- src/js/configs/validate.js
- src/sass/app.sass
- src/sass/components/decision-table.sass
- src/sass/components/form.sass
https://nebo15.atlassian.net/browse/GDF-350
> Validation error messages in form inputs

- src/js/controllers/tables-edit-controller.js
- src/js/modules/gandalf/models/table.js
- src/js/modules/gandalf/services/utils.js
https://nebo15.atlassian.net/browse/GDF-365
> Show save control on table model is changed

- src/js/controllers/history-list-controller.js
https://nebo15.atlassian.net/browse/GDF-355
> Reset history list on search string is empty

- src/jade/content/guides/decision-analytics.md
- src/jade/content/guides/tables-debugger.md
- src/jade/content/guides/tables-revisions.md
- src/jade/templates/tables-analytics.jade
- src/jade/templates/tables-debugger.jade
- src/jade/templates/tables-revisions.jade
https://nebo15.atlassian.net/browse/GDF-354
> Guidelines for table analytics, debugger and revisions

- src/jade/templates/directives/decision-rule-title-description.jade
- src/jade/templates/directives/decision-table.jade
- src/js/configs/language.js
https://nebo15.atlassian.net/browse/GDF-393
> Minlength and maxlength validations for table title and description

- src/js/modules/gandalf/models/project-user.js
https://nebo15.atlassian.net/browse/GDF-401
> Fix scopes in project user

- src/js/controllers/debugger-details-controller.js
https://nebo15.atlassian.net/browse/GDF-165
> Support variant_id in debugger

- src/jade/templates/history-details.jade
- src/jade/templates/history-list.jade
- src/js/modules/gandalf/models/history-table.js
https://nebo15.atlassian.net/browse/GDF-166
> Support variants in history

- src/jade/templates/sign-up.jade
- src/js/configs/language.js
https://nebo15.atlassian.net/browse/GDF-417
> Add validation pattern to username input

- src/jade/templates/directives/condition-input.jade
- src/jade/templates/directives/field.jade
- src/js/directives/condition-input.js
- src/sass/app.sass
https://nebo15.atlassian.net/browse/GDF-418
> Support number type in condition input

- src/jade/templates/directives/decision-table.jade
https://nebo15.atlassian.net/browse/GDF-420
> Fix sortable table rows

- src/jade/templates/directives/decision-table.jade
- src/jade/templates/tables-create.jade
- src/js/directives/components/select-matching-type.js
https://nebo15.atlassian.net/browse/GDF-444
> select matching type on table create

- src/js/modules/gandalf/models/project.js
https://nebo15.atlassian.net/browse/GDF-438
> Fix consumers in project settings

- src/jade/index.jade
- src/jade/templates/groups-details.jade
- src/jade/templates/tables-analytics.jade
- src/jade/templates/tables-create.jade
- src/jade/templates/tables-debugger.jade
- src/jade/templates/tables-details.jade
- src/jade/templates/tables-edit-variant.jade
- src/jade/templates/tables-edit.jade
- src/jade/templates/tables-revisions.jade
- src/js/app.js
- src/js/configs/auth.js
- src/js/configs/breadcrumbs.js
- src/js/configs/states/groups.js
- src/js/configs/states/history.js
- src/js/configs/states/settings.js
- src/js/configs/states/tables.js
https://nebo15.atlassian.net/browse/GDF-449
> Remove breadcrumb

- src/jade/templates/tables-create.jade
- src/js/directives/components/select-matching-type.js
- src/js/modules/gandalf/models/table.js
https://nebo15.atlassian.net/browse/GDF-446
> GDF-446: select matching type strict mode

- src/jade/templates/sign-in.jade
- src/js/configs/auth.js
- src/js/configs/language.js
- src/js/configs/states.js
- src/js/controllers/auth/sign-in-controller.js
https://nebo15.atlassian.net/browse/GDF-358
> GDF-358: errorCode support

- settings/config.json
- src/jade/templates/tables-details-variant-debugger.jade
- src/js/controllers/debugger-details-controller.js
https://nebo15.atlassian.net/browse/GDF-454
> GDF-454: move debugger host to the config

- bower.json
- src/jade/index.jade
- src/js/app.js
https://nebo15.atlassian.net/browse/GDF-388
> GDF-388: add ngSanitize

- src/jade/templates/tables-details-variant-debugger.jade
- src/js/controllers/debugger-details-controller.js
https://nebo15.atlassian.net/browse/GDF-455
> GDF-455: add variant id to the sample request string

- src/jade/templates/tables-details-edit.jade
https://nebo15.atlassian.net/browse/GDF-460
> Text overflow in table details variant list

- src/jade/templates/history-list.jade
- src/jade/templates/tables-details.jade
- src/js/configs/states/tables.js
- src/js/controllers/history-list-controller.js
https://nebo15.atlassian.net/browse/GDF-402
> Hystory table view

- .travis.yml
- gulpfile.js
- package.json
- protractor.config.js
- tests/.gitignore
- tests/README.md
- tests/caps.js
- tests/pages/dashboard_page.js
- tests/pages/debugger_page.js
- tests/pages/decisions_page.js
- tests/pages/history_page.js
- tests/pages/home_page.js
- tests/pages/new_project_page.js
- tests/pages/new_tables_page.js
- tests/pages/revisions_page.js
- tests/pages/settings_page.js
- tests/pages/table_page.js
- tests/pages/welcome_page.js
- tests/tests/Settings.js
- tests/tests/SignIn.js
- tests/tests/SignUp.js
- tests/tests/Tables.js
https://nebo15.atlassian.net/browse/GDF-387
> GDF-387: add tests

- src/js/modules/gandalf/services/gandalf.js
- src/js/services/auth.js
https://nebo15.atlassian.net/browse/GDF-472
> Refresh token

- src/js/configs/auth.js
https://nebo15.atlassian.net/browse/GDF-475
> Fix error code in sign-in page

- src/js/controllers/tables-edit-variant-controller.js
https://nebo15.atlassian.net/browse/GDF-474
https://nebo15.atlassian.net/browse/GDF-478
> Calculate table hash instead variant hash

- src/jade/index.jade
- src/jade/templates/reset-password-confirm.jade
- src/jade/templates/reset-password.jade
- src/jade/templates/sign-in.jade
- src/js/configs/language.js
- src/js/configs/states.js
- src/js/controllers/auth/reset-password-confirm-controller.js
- src/js/controllers/auth/reset-password-controller.js
- src/js/controllers/auth/sign-in-controller.js
- src/js/modules/gandalf/services/gandalf.js
- src/sass/app.sass
- src/sass/components/form.sass
https://nebo15.atlassian.net/browse/GDF-447
> GDF-447: reset password

- src/jade/content/invite-sign-up.md
- src/jade/templates/sign-up.jade
- src/js/configs/states.js
- src/js/controllers/auth/sign-up-controller.js
https://nebo15.atlassian.net/browse/GDF-453
> Add message if invite sign-up

- src/js/configs/states/settings.js
- src/js/modules/gandalf/services/gandalf.js
- src/js/services/user.js
https://nebo15.atlassian.net/browse/GDF-487
> Separate request for user in settings

- protractor.config.js
- tests/tests/Settings.js
> fix config

- src/jade/templates/settings/project.jade
- src/js/controllers/settings/settings-project-controller.js
- src/js/modules/gandalf/models/project.js
- src/js/modules/gandalf/services/gandalf.js
https://nebo15.atlassian.net/browse/GDF-362
API пока отдает 500
> Export project

- src/jade/content/activate-success.md
- src/jade/content/activate.md
- src/jade/index.jade
- src/jade/partitials/navbar-private.jade
- src/jade/templates/activate.jade
- src/jade/templates/layouts/public.jade
- src/jade/templates/modal/resend-activate-mail-success.jade
- src/jade/templates/settings/project.jade
- src/jade/templates/sign-up.jade
- src/jade/templates/welcome/index.jade
- src/jade/templates/welcome/send-email.jade
- src/js/configs/states.js
- src/js/configs/states/welcome.js
- src/js/controllers/auth/activate-controller.js
- src/js/controllers/settings/settings-project-controller.js
- src/js/controllers/welcome/welcome-controller.js
- src/js/modules/gandalf/models/user.js
- src/js/modules/gandalf/services/gandalf.js
- src/js/services/user.js
- src/sass/app.sass
https://nebo15.atlassian.net/browse/GDF-298
https://nebo15.atlassian.net/browse/GDF-297
https://nebo15.atlassian.net/browse/GDF-442
> Activate account pages, resend activate mail

- src/jade/templates/settings/project.jade
- src/js/controllers/settings/settings-project-controller.js
https://nebo15.atlassian.net/browse/GDF-493
> Export data: loader and disabled if file downloaded

- src/jade/templates/settings/project.jade
https://nebo15.atlassian.net/browse/GDF-498
> Change settings buttons position

- src/js/directives/components/user-edit.js
https://nebo15.atlassian.net/browse/GDF-496
> Fix cancel in user-edit directive

- src/jade/templates/tables-details-variant-edit_simple.jade
https://nebo15.atlassian.net/browse/GDF-497
> Title for matching type control in simple variant

- src/js/configs/states.js
- src/js/services/auth.js
https://nebo15.atlassian.net/browse/GDF-521
> Sign in, sign up - redirect to tables list where user authorized

- src/jade/partitials/navbar-private.jade
- src/jade/templates/error.jade
- src/js/configs/states.js
- src/js/configs/states/tables.js
- src/js/controllers/app-controller.js
- src/sass/app.sass
- src/sass/components/error-page.sass
https://nebo15.atlassian.net/browse/GDF-517
> Support 404 error on resolve data fail

- src/js/modules/gandalf/models/field.js
- src/js/modules/gandalf/models/rule.js
https://nebo15.atlassian.net/browse/GDF-527
> Add isDeleted property in toJSON for valid hash calculation

- src/jade/index.jade
- src/jade/partitials/navbar-right-user.jade
- src/jade/templates/modal/change-password.jade
- src/jade/templates/modal/profile-edit.jade
- src/js/configs/language.js
- src/js/directives/components/change-password.js
- src/js/directives/components/profile-edit.js
- src/js/modules/gandalf/models/user.js
- src/js/modules/gandalf/services/gandalf.js
- src/js/services/user.js
https://nebo15.atlassian.net/browse/GDF-494
Сейчас при ошибке смены пароля API отдает 401 и интерфейс ведет себя не корректно, когда починят (будут отдавать 422) все будет ок.
> Change username, email and password functional

- src/jade/templates/reset-password-confirm.jade
https://nebo15.atlassian.net/browse/GDF-531
> Reset pasword validation fixes

- src/jade/templates/reset-password-confirm.jade
- src/jade/templates/sign-up.jade
https://nebo15.atlassian.net/browse/GDF-501
> Hide password complexity where user no change password

- src/jade/templates/welcome/index.jade
https://nebo15.atlassian.net/browse/GDF-522
> Delete activate state in welcome, add text if user not active in welcome index

- src/js/modules/gandalf/services/gandalf.js
https://nebo15.atlassian.net/browse/GDF-532
> Add property `skipRefreshToken`

- src/js/controllers/history-details-controller.js
- src/js/modules/gandalf/models/history-table.js
https://nebo15.atlassian.net/browse/GDF-504
> Add defaultDecision property in history table model

- src/jade/partitials/navbar-private.jade
- src/jade/templates/settings/project.jade
- src/js/controllers/app-controller.js
- src/js/controllers/settings/settings-project-controller.js
https://nebo15.atlassian.net/browse/GDF-519
> Activate account changes

- src/jade/partitials/footer.jade
- src/sass/app.sass
https://nebo15.atlassian.net/browse/GDF-518
> Change global footer

- src/jade/index.jade
- src/jade/templates/tables-details-variant-edit.jade
- src/jade/templates/tables-details-variant-edit_simple.jade
- src/js/directives/validation-focus.js
https://nebo15.atlassian.net/browse/GDF-515
> Focus to invalid input in edit table page

- src/jade/templates/directives/condition-input.jade
- src/jade/templates/directives/decision-table.jade
- src/js/directives/components/decision-table.js
- src/js/directives/condition-input.js
https://nebo15.atlassian.net/browse/GDF-534
> Change validation in condition input

- src/js/modules/gandalf/constants/transforms.js
https://nebo15.atlassian.net/browse/GDF-526
> GDF-526: fix to json transformation

- src/js/directives/doubled-input.js
https://nebo15.atlassian.net/browse/GDF-535
> Parse to string double input value

- bower.json
- src/jade/index.jade
- src/js/app.js
- src/js/configs/toastr.js
https://nebo15.atlassian.net/browse/GDF-452
> GDF-452: Add toastr for backend errors

- src/jade/templates/directives/decision-input.jade
- src/js/configs/language.js
- src/js/configs/validate.js
- src/js/directives/components/decision-input.js
- src/js/directives/components/decision-rule-decision.js
https://nebo15.atlassian.net/browse/GDF-524
> Validate JSON and save decision on blur

- src/jade/templates/modal/user-add.jade
- src/js/configs/validate.js
- src/js/directives/components/user-add.js
- src/js/modules/gandalf/models/project.js
- src/js/modules/gandalf/services/gandalf.js
- src/js/modules/uib-modal-confirm.js
https://nebo15.atlassian.net/browse/GDF-525
> GDF-525: send user invitation

- src/jade/templates/directives/user-scope-list.jade
- src/jade/templates/modal/user-add.jade
- src/jade/templates/modal/user-edit.jade
- src/js/directives/components/user-scope-list.js
https://nebo15.atlassian.net/browse/GDF-536
> Verify user access for add/edit user

- src/js/controllers/auth/sign-in-controller.js
https://nebo15.atlassian.net/browse/GDF-541
> Clear message on submit in sign-in

- src/jade/templates/modal/add-project.jade
- src/jade/templates/welcome/project-add.jade
https://nebo15.atlassian.net/browse/GDF-542
> Project description not required

- src/jade/templates/directives/decision-input.jade
- src/jade/templates/directives/decision-table.jade
- src/jade/templates/tables-details-variant-edit_simple.jade
- src/sass/components/decision-table.sass
https://nebo15.atlassian.net/browse/GDF-545
> User access in decision table fixes
